[package]
name = "cere-runtime-constants"
version = "4.8.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
node-primitives = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }

[features]
default = ["std"]
std = [
  "node-primitives/std",
]
