version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "dev"
    reviewers: ["security-team"]
    assignees: ["security-team"]
    commit-message:
      prefix: "security"
      prefix-development: "cargo"
    groups:
      security-updates:
        patterns: ["*"]
        update-types: ["security"]
      patch-updates:
        patterns: ["*"]
        update-types: ["patch"]
    # Only allow security updates by default
    open-pull-requests-limit: 10

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    target-branch: "dev"
    reviewers: ["security-team"]
    commit-message:
      prefix: "ci"
      prefix-development: "actions"
    # Keep actions up to date for security
    open-pull-requests-limit: 5

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    target-branch: "dev"
    reviewers: ["security-team"]
    commit-message:
      prefix: "docker"
    # Only security updates for base images
    open-pull-requests-limit: 3 
