# cargo-deny configuration for security enforcement
# This file is part of the comprehensive testing framework implementation

[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "wasm32-unknown-unknown" },
]

[licenses]
# Security: Only allow approved licenses
confidence-threshold = 0.8
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "GPL-3.0-or-later WITH Classpath-exception-2.0",
]

# Deny copyleft licenses except for our own GPL-3.0
deny = [
  "GPL-2.0",
  "GPL-3.0",
  "AGPL-1.0",
  "AGPL-3.0",
  "LGPL-2.0",
  "LGPL-2.1",
  "LGPL-3.0",
]

[[licenses.exceptions]]
allow = ["GPL-3.0-or-later WITH Classpath-exception-2.0"]
name = "cere-runtime"

[[licenses.exceptions]]
allow = ["GPL-3.0-or-later WITH Classpath-exception-2.0"]
name = "cere-dev-runtime"

[bans]
# Security: Deny known vulnerable crates
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

# Deny specific vulnerable or problematic crates
deny = [
  # Known security vulnerabilities
  { name = "openssl", version = "*" },
  { name = "openssl-sys", version = "<0.9.60" },
  
  # Cryptographically broken
  { name = "md5", version = "*" },
  { name = "sha1", version = "*" },
  
  # Unmaintained or problematic
  { name = "tempdir", version = "*" },
  { name = "net2", version = "*" },
]

# Allow certain duplicates that are hard to resolve in blockchain ecosystem
skip = [
  { name = "windows-sys" },          # Common in many deps
  { name = "windows_x86_64_msvc" },  # Windows-specific
  { name = "syn" },                  # Multiple versions common
  { name = "proc-macro2" },          # Proc macro ecosystem
]

skip-tree = [
  { name = "substrate-build-script-utils" },
  { name = "substrate-wasm-builder" },
]

[advisories]
# Security: Check against RustSec advisory database
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
yanked = "warn"
notice = "warn"

# Ignore specific advisories if needed (with justification)
ignore = [
  # Add specific RUSTSEC IDs here if needed with justification
  # "RUSTSEC-YYYY-NNNN",  # Justification: reason why this is acceptable
]

[sources]
# Security: Only allow crates from known sources
unknown-registry = "warn"
unknown-git = "warn"

[sources.allow-registry]
# Only allow crates.io and our private registries
allow = ["https://github.com/rust-lang/crates.io-index"]

[sources.allow-git]
# Allow specific Git dependencies we control
allow = [
  "https://github.com/Cerebellum-Network/*",
  "https://github.com/paritytech/*",
  "https://github.com/substrate-developer-hub/*",
] 
