[toolchain]
<<<<<<< HEAD
<<<<<<< HEAD
channel = "1.79.0"
=======
channel = "nightly-2024-03-12"
>>>>>>> 656e5410 (Fix/staking migrations (#300))
components = ["clippy", "rustfmt"]
=======
channel = "1.77.0"
components = ["clippy"]
>>>>>>> 7ad744e7 (Enable Clippy (#324))
targets = ["wasm32-unknown-unknown"]
