[relaychain]
default_command = "./target/release/cere"
default_args = [""]
chain = "local"

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[relaychain.nodes]]
name = "charlie"

[[relaychain.nodes]]
name = "dave"

[[relaychain.nodes]]
name = "eve"

[[relaychain.nodes]]
name = "ferdie"
validator = false
