//! Autogenerated weights for pallet_ddc_verification
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-01-23, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `bench`, CPU: `AMD EPYC Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/cere
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --pallet=pallet_ddc_verification
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/frame-weight-template.hbs
// --output=pallets/ddc-verification/src/weights3.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_ddc_verification.
pub trait WeightInfo {
	fn set_validator_key() -> Weight;
	fn commit_payout_fingerprint() -> Weight;
	fn begin_payout() -> Weight;
	fn begin_charging_customers() -> Weight;
	fn send_charging_customers_batch(b: u32, ) -> Weight;
	fn end_charging_customers() -> Weight;
	fn begin_rewarding_providers() -> Weight;
	fn send_rewarding_providers_batch(b: u32, ) -> Weight;
	fn end_rewarding_providers() -> Weight;
	fn end_payout() -> Weight;
	fn emit_consensus_errors(b: u32, ) -> Weight;
	fn force_skip_inspection() -> Weight;
	fn force_set_validator_key() -> Weight;
}

/// Weights for pallet_ddc_verification using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: `Staking::Ledger` (r:1 w:0)
	// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Staking::Bonded` (r:1 w:0)
	// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorToStashKey` (r:0 w:1)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_validator_key() -> Weight {
		Weight::from_parts(47_030_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcClusters::Clusters` (r:1 w:0)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn commit_payout_fingerprint() -> Weight {
		Weight::from_parts(50_536_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:0)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn begin_payout() -> Weight {
		Weight::from_parts(44_564_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn begin_charging_customers() -> Weight {
		Weight::from_parts(38_613_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:0)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcCustomers::Ledger` (r:500 w:500)
	// Proof: `DdcCustomers::Ledger` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:2 w:2)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `DdcPayouts::DebtorCustomers` (r:489 w:489)
	// Proof: `DdcPayouts::DebtorCustomers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 500]`.
	fn send_charging_customers_batch(b: u32, ) -> Weight {
		Weight::from_parts(138_341_000_u64, 0)
			// Standard Error: 222_721
			.saturating_add(Weight::from_parts(64_602_746_u64, 0).saturating_mul(b as u64))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b as u64)))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b as u64)))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcClusters::ClustersGovParams` (r:1 w:0)
	// Proof: `DdcClusters::ClustersGovParams` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:3 w:3)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `DdcClusters::Clusters` (r:1 w:0)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Staking::Validators` (r:2 w:0)
	// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	// Storage: `Staking::Bonded` (r:1 w:0)
	// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	// Storage: `Staking::Ledger` (r:1 w:0)
	// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Staking::Nominators` (r:1 w:0)
	// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(558), added: 3033, mode: `MaxEncodedLen`)
	fn end_charging_customers() -> Weight {
		Weight::from_parts(272_346_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn begin_rewarding_providers() -> Weight {
		Weight::from_parts(39_213_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:0)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:316 w:316)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 500]`.
	fn send_rewarding_providers_batch(b: u32, ) -> Weight {
		Weight::from_parts(1_956_633_025_u64, 0)
			// Standard Error: 459_599
			.saturating_add(Weight::from_parts(41_100_944_u64, 0).saturating_mul(b as u64))
			.saturating_add(T::DbWeight::get().reads(48_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b as u64)))
			.saturating_add(T::DbWeight::get().writes(45_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b as u64)))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn end_rewarding_providers() -> Weight {
		Weight::from_parts(39_716_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcClusters::Clusters` (r:1 w:1)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn end_payout() -> Weight {
		Weight::from_parts(57_348_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 5]`.
	fn emit_consensus_errors(b: u32, ) -> Weight {
		Weight::from_parts(21_243_502_u64, 0)
			// Standard Error: 16_284
			.saturating_add(Weight::from_parts(3_208_119_u64, 0).saturating_mul(b as u64))
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	// Storage: `DdcClusters::Clusters` (r:1 w:1)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:0 w:1)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:0 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_skip_inspection() -> Weight {
		Weight::from_parts(41_167_000_u64, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn force_set_validator_key() -> Weight {
		Weight::from_parts(41_167_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: `Staking::Ledger` (r:1 w:0)
	// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Staking::Bonded` (r:1 w:0)
	// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorToStashKey` (r:0 w:1)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_validator_key() -> Weight {
		Weight::from_parts(47_030_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcClusters::Clusters` (r:1 w:0)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn commit_payout_fingerprint() -> Weight {
		Weight::from_parts(50_536_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:0)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn begin_payout() -> Weight {
		Weight::from_parts(44_564_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn begin_charging_customers() -> Weight {
		Weight::from_parts(38_613_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:0)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcCustomers::Ledger` (r:500 w:500)
	// Proof: `DdcCustomers::Ledger` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:2 w:2)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `DdcPayouts::DebtorCustomers` (r:489 w:489)
	// Proof: `DdcPayouts::DebtorCustomers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 500]`.
	fn send_charging_customers_batch(b: u32, ) -> Weight {
		Weight::from_parts(138_341_000_u64, 0)
			// Standard Error: 222_721
			.saturating_add(Weight::from_parts(64_602_746_u64, 0).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(b as u64)))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(b as u64)))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcClusters::ClustersGovParams` (r:1 w:0)
	// Proof: `DdcClusters::ClustersGovParams` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:3 w:3)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `DdcClusters::Clusters` (r:1 w:0)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Staking::Validators` (r:2 w:0)
	// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	// Storage: `Staking::Bonded` (r:1 w:0)
	// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	// Storage: `Staking::Ledger` (r:1 w:0)
	// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Staking::Nominators` (r:1 w:0)
	// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(558), added: 3033, mode: `MaxEncodedLen`)
	fn end_charging_customers() -> Weight {
		Weight::from_parts(272_346_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn begin_rewarding_providers() -> Weight {
		Weight::from_parts(39_213_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:1 w:0)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `System::Account` (r:316 w:316)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 500]`.
	fn send_rewarding_providers_batch(b: u32, ) -> Weight {
		Weight::from_parts(1_956_633_025_u64, 0)
			// Standard Error: 459_599
			.saturating_add(Weight::from_parts(41_100_944_u64, 0).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(48_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(b as u64)))
			.saturating_add(RocksDbWeight::get().writes(45_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b as u64)))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn end_rewarding_providers() -> Weight {
		Weight::from_parts(39_716_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:1 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcClusters::Clusters` (r:1 w:1)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn end_payout() -> Weight {
		Weight::from_parts(57_348_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: `DdcVerification::ValidatorToStashKey` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorToStashKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcVerification::ValidatorSet` (r:1 w:0)
	// Proof: `DdcVerification::ValidatorSet` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 5]`.
	fn emit_consensus_errors(b: u32, ) -> Weight {
		Weight::from_parts(21_243_502_u64, 0)
			// Standard Error: 16_284
			.saturating_add(Weight::from_parts(3_208_119_u64, 0).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	// Storage: `DdcClusters::Clusters` (r:1 w:1)
	// Proof: `DdcClusters::Clusters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutFingerprints` (r:0 w:1)
	// Proof: `DdcPayouts::PayoutFingerprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `DdcPayouts::PayoutReceipts` (r:0 w:1)
	// Proof: `DdcPayouts::PayoutReceipts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_skip_inspection() -> Weight {
		Weight::from_parts(41_167_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn force_set_validator_key() -> Weight {
		Weight::from_parts(41_167_000_u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}