[package]
name = "cere-dev-runtime-constants"
version = "4.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
node-primitives = { version = "2.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }

[features]
default = ["std"]
std = [
	"sp-runtime/std"
]
