[package]
name = "cere-runtime-common"
version = "4.7.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[features]
default = ["std"]
no_std = []
std = []

[dependencies]
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.29" }
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.29" }
node-primitives = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.29" }
