[package]
name = "cere-runtime-common"
version = "4.8.8"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
frame-support = { workspace = true }
node-primitives = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
no_std = []
std = [
  "frame-support/std",
  "node-primitives/std",
  "sp-core/std",
  "sp-runtime/std",
]
