[package]
name = "cere-runtime-common"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true }
log = { workspace = true, default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

ddc-primitives = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-contracts = { workspace = true }
pallet-referenda = { workspace = true }
pallet-session = { workspace = true }
pallet-timestamp = { workspace = true }
scale-info = { workspace = true }
sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-staking = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
no_std = []
std = [
  "codec/std",
  "log/std",
  "serde",
  "serde_json",
  "ddc-primitives/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-contracts/std",
  "pallet-referenda/std",
  "pallet-session/std",
  "pallet-timestamp/std",
  "scale-info/std",
  "sp-api/std",
  "sp-arithmetic/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-staking/std",
  "sp-std/std",
]
