# Phase 4: AlertManager Configuration
# Alert routing and notification management for Cere blockchain security monitoring

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cere.network'
  smtp_auth_username: 'alerts@cere.network'
  smtp_auth_password: 'smtp_password_change_me'

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance']

  - source_match:
      alertname: 'NodeDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']

# Route tree for alert distribution
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical security alerts - immediate notification
    - match:
        severity: critical
      receiver: 'security-team-critical'
      group_wait: 0s
      repeat_interval: 5m
      routes:
        - match:
            category: security
          receiver: 'security-team-immediate'
          group_wait: 0s
          repeat_interval: 1m

    # High priority alerts
    - match:
        severity: high
      receiver: 'security-team-high'
      group_wait: 30s
      repeat_interval: 15m

    # Warning alerts
    - match:
        severity: warning
      receiver: 'ops-team'
      group_wait: 5m
      repeat_interval: 1h

    # Compliance alerts
    - match:
        category: compliance
      receiver: 'compliance-team'
      group_wait: 1m
      repeat_interval: 30m

    # System health alerts
    - match:
        category: system
      receiver: 'ops-team'
      group_wait: 2m
      repeat_interval: 30m

# Notification receivers
receivers:
  - name: 'default'
    email_configs:
      - to: 'devops@cere.network'
        subject: '[Cere Blockchain] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'security-team-immediate'
    email_configs:
      - to: 'security-critical@cere.network'
        subject: '🚨 CRITICAL SECURITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          IMMEDIATE ACTION REQUIRED
          
          {{ range .Alerts }}
          🚨 CRITICAL SECURITY ALERT 🚨
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          This is a critical security alert requiring immediate attention.
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#security-alerts'
        title: '🚨 CRITICAL SECURITY ALERT'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        send_resolved: true

  - name: 'security-team-critical'
    email_configs:
      - to: 'security@cere.network'
        subject: '🔴 Critical Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Critical Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#security-alerts'
        title: '🔴 Critical Alert'
        send_resolved: true

  - name: 'security-team-high'
    email_configs:
      - to: 'security@cere.network'
        subject: '🟠 High Priority Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          High Priority Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'compliance-team'
    email_configs:
      - to: 'compliance@cere.network'
        subject: '📋 Compliance Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Compliance Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Category: {{ .Labels.category }}
          
          This alert may affect compliance requirements.
          Please review and take appropriate action.
          {{ end }}

  - name: 'ops-team'
    email_configs:
      - to: 'ops@cere.network'
        subject: '⚠️ Operations Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Operations Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#ops-alerts'
        title: '⚠️ Operations Alert'
        send_resolved: true

# Templates for custom notification formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'