# Network Security Configuration for Cere Blockchain Node
# This file contains security settings for peer-to-peer networking

[network]
# Minimum number of peers required for healthy network operation
min_peers = 3

# Maximum number of peers to maintain connections with
max_peers = 50

# Preferred number of peers for optimal performance
preferred_peers = 25

# Block time threshold in milliseconds (2x expected block time)
block_time_threshold_ms = 12000

# Network monitoring interval in seconds
monitoring_interval_secs = 30

[security]
# Minimum reputation score for peers (0-100)
reputation_threshold = 50

# Maximum allowed message rate per peer (messages per second)
max_message_rate = 100

# Enable peer reputation system
enable_reputation_system = true

# Enable network health monitoring
enable_health_monitoring = true

# Enable malicious peer detection
enable_malicious_detection = true

[consensus]
# Minimum consensus participation rate (percentage)
min_consensus_rate = 90.0

# Maximum allowed consensus failures before alert
max_consensus_failures = 5

# GRANDPA justification period
grandpa_justification_period = 512

[libp2p]
# Enable Kademlia DHT
enable_kademlia = true

# Enable mDNS discovery (only for local networks)
enable_mdns = false

# Connection limits
max_pending_incoming = 10
max_pending_outgoing = 10
max_established_incoming = 25
max_established_outgoing = 25

# Transport security
enable_noise = true
enable_yamux = true

# Connection timeout in seconds
connection_timeout_secs = 30

# Keep-alive interval in seconds
keep_alive_interval_secs = 10

[firewall]
# Enable basic firewall rules
enable_firewall = true

# Allowed IP ranges (CIDR notation)
allowed_ranges = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
]

# Blocked IP ranges
blocked_ranges = [
    "127.0.0.0/8",  # Localhost (except for development)
    "169.254.0.0/16", # Link-local
    "224.0.0.0/4"   # Multicast
]

# Rate limiting
max_connections_per_ip = 5
connection_rate_limit_per_minute = 60

[monitoring]
# Enable Prometheus metrics
enable_prometheus = true

# Metrics collection interval in seconds
metrics_interval_secs = 15

# Enable detailed peer metrics
enable_peer_metrics = true

# Enable consensus metrics
enable_consensus_metrics = true

# Enable network health alerts
enable_health_alerts = true

[alerts]
# Webhook URL for security alerts (optional)
# webhook_url = "https://your-monitoring-system.com/webhook"

# Email notifications (optional)
# smtp_server = "smtp.example.com"
# smtp_port = 587
# smtp_username = "alerts@example.com"
# smtp_password = "password"
# alert_recipients = ["admin@example.com"]

# Alert thresholds
low_peer_count_threshold = 3
low_security_score_threshold = 70
high_consensus_failure_threshold = 5
network_partition_threshold = 60  # seconds

[development]
# Development mode settings (only for local/dev networks)
allow_localhost_peers = false
allow_private_ips = true
disable_peer_verification = false
enable_debug_logging = false

# Test network specific settings
[development.testnet]
allow_localhost_peers = true
min_peers = 1
max_peers = 10

[development.devnet]
allow_localhost_peers = true
min_peers = 1
max_peers = 5
enable_debug_logging = true