[package]
name = "ddc-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
ddc-primitives = { version = "0.1.0", default-features = false, path = "../primitives" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }
