[package]
name = "ddc-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
ddc-primitives = { path = "../primitives", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30", default-features = false }
