[package]
name = "sc-network-types"
version = "0.15.5"
edition = "2021"

[dependencies]
bs58 = { version = "0.5.0", default-features = false, features = ["alloc"] }
bytes = { version = "1.4.0", default-features = false }
ed25519-dalek = { version = "2.0.0", default-features = false, features = ["rand_core"] }
libp2p-identity = { version = "0.2.9", default-features = false }
libp2p-kad = { version = "0.46.0", default-features = false }
litep2p = { version = "0.9.0", default-features = false }
log = { version = "0.4.17", default-features = false }
multiaddr = { version = "0.18.0", default-features = false }
multihash = { version = "0.19.0", default-features = false }
parity-scale-codec = { version = "3.6.0", default-features = false, features = ["derive"] }
rand = { version = "0.8.5", default-features = false }
thiserror = { version = "1.0.0", default-features = false }
zeroize = { version = "1.8.0", default-features = false }

[features]
default = []
std = []
