[package]
name = "sc-network-types"
version = "0.15.5"
edition = "2021"

[dependencies]
array-bytes = "6.2.3"
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false, features = ["derive"] }
libp2p = "0.54.1"
multiaddr = "0.18.2"
multihash = "0.19.3"
scale-info = { version = "2.11.3", default-features = false, features = ["derive"] }
