[relaychain]
default_command = "./target/release/cere"
chain = "local"

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[relaychain.nodes]]
name = "charlie"
<<<<<<< HEAD
<<<<<<< HEAD
=======


>>>>>>> 5c9162c1 (fix zombienet issue)
=======
>>>>>>> 6f3db528 (fmt)
