name: CEF PR Tracker

on:
  pull_request:
    types: [opened, closed, reopened, synchronize] #Customize to when you want it to run

jobs:
  send-pr-event:
    runs-on: ubuntu-latest
    steps:
      - uses: cere-io/cef-github-action@main
        with:
          wallet_uri:     ${{ secrets.WALLET_URI }}
          ddc_base_url:   ${{ secrets.CEF_DDC_BASE_URL }}
          agent_service:  ${{ secrets.CEF_AGENT_SERVICE }}
          workspace:      ${{ secrets.CEF_WORKSPACE }}
          stream:         ${{ secrets.CEF_STREAM }}
          notion_page_id: ${{ secrets.NOTION_PAGE_ID }}
          notion_api_key: ${{ secrets.NOTION_API_KEY }}
          slack_productivity_bot_token: ${{ secrets.SLACK_PRODUCTIVITY_BOT_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }} 