name: CI

on:
  pull_request:
    branches:
      - dev
      - master
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    types:
      - opened
      - synchronize
      - edited

env:
  PROFILE: release

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}:role/github
          role-session-name: ${{ github.event.repository.name }}
          aws-region: us-west-2

      - name: Get short SHA
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.tests
          push: false
          build-args: |
            "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}"
            "AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}"
            "AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}"
            "SCCACHE_REGION=us-west-2"
            "SCCACHE_BUCKET=cere-blockchain-sccache"

      - name: Build and push docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}"
            "AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}"
            "AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}"
            "SCCACHE_REGION=us-west-2"
            "SCCACHE_BUCKET=cere-blockchain-sccache"

          tags: |
            ${{ steps.login-ecr.outputs.registry }}/pos-network-node:${{ github.sha }}


      # TODO: paveltabalko to add e2e-tests simulations
