name: Release to dev
on:
  push:
    branches:
      - 'ci/**'
  workflow_dispatch:

env:
  PROFILE: dev
  # SCCACHE_RECACHE: 1 # Uncomment this to clear cache, then comment it back out
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-10-09
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.15.8"

      - name: Build
        run: cargo build --${{ env.PROFILE }}

      - uses: actions/upload-artifact@v3
        with:
          name: cargo
          path: |
            target/${{ env.PROFILE }}/cere
            target/${{ env.PROFILE }}/wbuild/cere-runtime/
            target/${{ env.PROFILE }}/wbuild/cere-dev-runtime/
          if-no-files-found: error

  deploy-to-ecr:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    needs: build
    with:
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: pos-network-node
      file: ./Dockerfile-new
      build_artifact: cargo
    secrets: inherit
