name: Release to dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    with:
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: pos-network-node
    secrets: inherit
