name: Release to dev
on:
  push:
    branches:
      - 'ci/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-10-09
          override: true
          components: rustfmt, clippy

      - name: Restore cached
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.15.8"

      - run: cargo build --release

      - uses: actions/upload-artifact@v3
        with:
          name: cargo
          path: |
            target/release/cere
            target/release/wbuild/cere-runtime/
            target/release/wbuild/cere-dev-runtime/
          if-no-files-found: error

  deploy-to-ecr:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    needs: build
    with:
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: pos-network-node
      file: ./Dockerfile-new
      build_artifact: cargo
    secrets: inherit
