<<<<<<< HEAD
<<<<<<< HEAD
name: ECR

on:
  push:
    branches:
      - berlin-hackaton

env:
  PROFILE: release

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: dev
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Configure AWS credentials ORG
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR ORG
        id: login-ecr-org
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image to ECR Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.tests
          push: true
          build-args: |
            "ECR_REGISTRY=${{ steps.login-ecr-org.outputs.registry }}-berlin"
<<<<<<< HEAD
<<<<<<< HEAD
=======
name: "Build Berlin Hackathon branch"
=======
name: ECR
>>>>>>> 39ccd36a (Update docker-image-berlin.yml)

on:
  push:
    branches:
      - berlin-hackaton

env:
  PROFILE: release

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: dev
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Configure AWS credentials ORG
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR ORG
        id: login-ecr-org
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image to ECR Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.tests
          push: true
          build-args: |
<<<<<<< HEAD
            COMMIT=${{ github.sha }}
            VERSION=${{ github.sha }}
            NETWORK=local
>>>>>>> 1673139f (Create docker-image-berlin.yml)
=======
            "ECR_REGISTRY=${{ steps.login-ecr-org.outputs.registry }}-berlin"
>>>>>>> 39ccd36a (Update docker-image-berlin.yml)
=======
>>>>>>> 33240126 (OCW-DAC-Validation changes (#397))
=======
>>>>>>> 288e93b6 (refactoring)
