name: Berlin docker image build and push

on:
  push:
    branches:
      - berlin-hackaton

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: [self-hosted, cere-network-large]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}:role/github
          role-session-name: ${{ github.event.repository.name }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Process version
        id: version
        run: |
          echo "image_tag=berlin-${{ github.run_attempt}}-$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build and push docker image to ECR Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.tests
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/pos-network-node:${{ env.image_tag }}