name: ECR

on:
  push:
    branches:
      - dev
      - staging
      - master
      - 'fix_ci'
  pull_request:
    branches:
      - 'release/**'
      - 'hotfix/**'
    types:
      - opened
      - synchronize
      - edited

env:
  PROFILE: release

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: dev
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Debug - Check GH_READ_TOKEN
        run: |
          echo "GH_READ_TOKEN length: ${#GH_READ_TOKEN}"
          echo "GH_READ_TOKEN is set: $([ -n "$GH_READ_TOKEN" ] && echo "YES" || echo "NO")"
          echo "First 10 chars: ${GH_READ_TOKEN:0:10}"

      - name: Configure Git
        run: |
          if [ -n "${{ secrets.GH_READ_TOKEN }}" ]; then
            git config --global url."https://${{ secrets.GH_READ_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          else
            echo "Using GITHUB_TOKEN as fallback"
            git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          fi

      - name: Cache cargo registry
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Configure AWS credentials ORG
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR ORG
        id: login-ecr-org
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image to ECR Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.tests
          push: false
          build-args: |
            "ECR_REGISTRY=${{ steps.login-ecr-org.outputs.registry }}"
            "GH_READ_TOKEN=${{ secrets.GH_READ_TOKEN || github.token }}"
