name: Integration Tests

on:
  push:
    branches: [dev, staging, master]
  pull_request:
    branches: [dev, staging, master, 'release/**', 'hotfix/**']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read
  actions: read

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y clang libssl-dev llvm libudev-dev protobuf-compiler

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          override: true
          target: wasm32-unknown-unknown
          components: rust-src

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: Configure Git for private dependencies
        run: git config --global url."https://${{ secrets.GH_READ_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build release binary
        run: |
          cargo build --release --features runtime-benchmarks

      - name: Run key integration tests
        run: |
          # Test core pallets only (fastest tests)
          cargo test --package pallet-ddc-clusters --release --no-fail-fast
          cargo test --package pallet-ddc-nodes --release --no-fail-fast

      - name: Test WASM runtime builds
        run: |
          # Verify WASM files exist
          test -f target/release/wbuild/cere-runtime/cere_runtime.compact.compressed.wasm
          echo "✅ WASM runtime verified"

      - name: Test basic chain functionality
        run: |
          # Quick node startup test (10 seconds only)
          timeout 15s ./target/release/cere --dev --tmp &
          NODE_PID=$!
          sleep 5
          kill $NODE_PID || true
          wait $NODE_PID || true
          echo "✅ Node startup verified"

  compatibility-tests:
    name: Compatibility Tests  
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y clang libssl-dev llvm libudev-dev protobuf-compiler

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          override: true
          target: wasm32-unknown-unknown
          components: rust-src

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: Configure Git for private dependencies
        run: git config --global url."https://${{ secrets.GH_READ_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Test compilation only
        run: |
          # Just verify compilation works
          cargo check --features runtime-benchmarks
          cargo check --features try-runtime
          echo "✅ Compilation compatibility verified"
