name: Integration Tests

on:
  push:
    branches: [dev, staging, master]
  pull_request:
    branches: [dev, staging, master, 'release/**', 'hotfix/**']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  basic-checks:
    name: Basic Integration Checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          override: true
          target: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: Configure Git for private dependencies
        run: git config --global url."https://${{ secrets.GH_READ_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Quick compilation check
        run: |
          # Only check core compilation without building
          cargo check --lib
          echo "✅ Basic compilation verified"

      - name: Verify project structure
        run: |
          # Just verify key files exist
          test -f Cargo.toml
          test -d pallets/
          test -d runtime/
          echo "✅ Project structure verified"
