name: Publish docker image to DockerHub
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ECR_REPOSITORY: pos-network-node
  DOCKERHUB_REPOSITORY: cerebellumnetwork
  PACKAGE_NAME: pos-node
jobs:
  tag-and-push:
    runs-on: [self-hosted, cere-network-xlarge]
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.SHARED_AWS_ACCOUNT_ID }}:role/github
          role-session-name: ${{ github.event.repository.name }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull image from ECR and change name, push tagged version to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:${GITHUB_REF##*/}
          docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}
          docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish image to DockerHub
        id: docker_publish
        run: |
          docker push -a $DOCKERHUB_REPOSITORY/$PACKAGE_NAME
      - name: Image digest
        run: echo ${{ steps.docker_publish.outputs.digest }}
