name: Run tests
on:
  pull_request:
    branches:
      - dev
      - master
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    types:
      - opened
      - synchronize
      - edited

jobs:
  run-tests:
    runs-on: [self-hosted, cere-network-xlarge-workers]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free space
        run: df -h
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Run tests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker build --build-arg ECR_REGISTRY=$ECR_REGISTRY -f Dockerfile.tests -t pos-network-node:test .
      - name: Free space
        run: df -h
